package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"path"
	"sort"
	"strings"
	"unicode"
)

const generatedHeader = "// Code generated by vihren-gen. DO NOT EDIT.\n\n"

// RenderPackage renders the generated Go file for one discovered package.
func RenderPackage(pkg DiscoveredPackage) ([]byte, error) {
	if len(pkg.Markers) == 0 {
		return nil, fmt.Errorf("package %q has no vihren markers", pkg.ImportPath)
	}
	rendered, err := newPackageRender(pkg)
	if err != nil {
		return nil, err
	}
	return rendered.render()
}

type packageRender struct {
	pkg        DiscoveredPackage
	activities []markerRender
	workflows  []markerRender
	receivers  []receiverRender
	imports    *importSet
}

type markerRender struct {
	marker       DiscoveredMarker
	constName    string
	params       []parameterRender
	outputType   string
	receiverName string
}

type parameterRender struct {
	name string
	typ  string
}

type receiverRender struct {
	typeName string
	param    string
	pointer  bool
}

func newPackageRender(pkg DiscoveredPackage) (*packageRender, error) {
	staticImports := map[string]string{
		"worker": "go.temporal.io/sdk/worker",
	}
	hasActivity := hasMarkerKind(pkg.Markers, ActivityMarker)
	hasWorkflow := hasMarkerKind(pkg.Markers, WorkflowMarker)
	if hasActivity {
		staticImports["activity"] = "go.temporal.io/sdk/activity"
		staticImports["workflow"] = "go.temporal.io/sdk/workflow"
	}
	if hasWorkflow {
		staticImports["client"] = "go.temporal.io/sdk/client"
		staticImports["context"] = "context"
		staticImports["workflow"] = "go.temporal.io/sdk/workflow"
	}
	imports := newImportSet(pkg.types, staticImports)
	renderer := &typeRenderer{imports: imports}
	rendered := &packageRender{pkg: pkg, imports: imports}
	for _, marker := range pkg.Markers {
		if marker.signature == nil {
			return nil, fmt.Errorf("%s has no typed signature", marker.FunctionName)
		}
		item := markerRender{
			marker:    marker,
			constName: markerConstName(marker),
			params:    renderedBusinessParameters(renderer, marker),
		}
		if marker.HasOutput {
			item.outputType = renderer.render(marker.signature.Results().At(0).Type())
		}
		switch marker.Kind {
		case ActivityMarker:
			item.receiverName = receiverParamName(marker.ReceiverName)
			rendered.activities = append(rendered.activities, item)
		case WorkflowMarker:
			rendered.workflows = append(rendered.workflows, item)
		default:
			return nil, fmt.Errorf("unknown marker kind %q", marker.Kind)
		}
	}
	rendered.receivers = receiverRenders(rendered.activities)
	sort.Slice(rendered.activities, func(i int, j int) bool {
		return rendered.activities[i].marker.ProxyName < rendered.activities[j].marker.ProxyName
	})
	sort.Slice(rendered.workflows, func(i int, j int) bool {
		return rendered.workflows[i].marker.FunctionName < rendered.workflows[j].marker.FunctionName
	})
	return rendered, nil
}

func (rendered *packageRender) render() ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString(generatedHeader)
	buffer.WriteString("package ")
	buffer.WriteString(rendered.pkg.Name)
	buffer.WriteString("\n\n")
	rendered.renderImports(&buffer)
	rendered.renderConstants(&buffer)
	rendered.renderRegistryInterfaces(&buffer)
	rendered.renderActivities(&buffer)
	rendered.renderWorkflows(&buffer)
	rendered.renderRegister(&buffer)
	rendered.renderClient(&buffer)
	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated package %s: %w\n%s", rendered.pkg.ImportPath, err, buffer.String())
	}
	return formatted, nil
}

func (rendered *packageRender) renderImports(buffer *bytes.Buffer) {
	imports := rendered.imports.list()
	if len(imports) == 0 {
		return
	}
	buffer.WriteString("import (\n")
	for _, spec := range imports {
		buffer.WriteString("\t")
		if spec.name != "" && spec.name != path.Base(spec.importPath) {
			buffer.WriteString(spec.name)
			buffer.WriteString(" ")
		}
		buffer.WriteString(fmt.Sprintf("%q\n", spec.importPath))
	}
	buffer.WriteString(")\n\n")
}

func (rendered *packageRender) renderRegistryInterfaces(buffer *bytes.Buffer) {
	if len(rendered.activities) > 0 {
		buffer.WriteString("// activityRegistry is the minimal worker-side activity registration surface used by generated code.\n")
		buffer.WriteString("type activityRegistry interface {\n")
		buffer.WriteString("\tRegisterActivityWithOptions(activityFunc any, options activity.RegisterOptions)\n")
		buffer.WriteString("}\n\n")
	}
	if len(rendered.workflows) > 0 {
		buffer.WriteString("// workflowRegistry is the minimal worker-side workflow registration surface used by generated code.\n")
		buffer.WriteString("type workflowRegistry interface {\n")
		buffer.WriteString("\tRegisterWorkflowWithOptions(workflowFunc any, options workflow.RegisterOptions)\n")
		buffer.WriteString("}\n\n")
	}
}

func (rendered *packageRender) renderConstants(buffer *bytes.Buffer) {
	buffer.WriteString("const (\n")
	for _, activity := range rendered.activities {
		buffer.WriteString("\t// ")
		buffer.WriteString(activity.constName)
		buffer.WriteString(" is the derived Temporal activity type.\n")
		buffer.WriteString("\t")
		buffer.WriteString(activity.constName)
		buffer.WriteString(" = ")
		buffer.WriteString(fmt.Sprintf("%q", activity.marker.TemporalName))
		buffer.WriteString("\n\n")
	}
	for _, workflow := range rendered.workflows {
		buffer.WriteString("\t// ")
		buffer.WriteString(workflow.constName)
		buffer.WriteString(" is the derived Temporal workflow type.\n")
		buffer.WriteString("\t")
		buffer.WriteString(workflow.constName)
		buffer.WriteString(" = ")
		buffer.WriteString(fmt.Sprintf("%q", workflow.marker.TemporalName))
		buffer.WriteString("\n\n")
	}
	buffer.WriteString(")\n\n")
}

func (rendered *packageRender) renderActivities(buffer *bytes.Buffer) {
	buffer.WriteString("// RegisterActivities registers this package's generated activities.\n")
	buffer.WriteString("func RegisterActivities(r ")
	if len(rendered.activities) > 0 {
		buffer.WriteString("activityRegistry")
	} else {
		buffer.WriteString("worker.Registry")
	}
	for _, receiver := range rendered.receivers {
		buffer.WriteString(", ")
		buffer.WriteString(receiver.param)
		buffer.WriteString(" ")
		if receiver.pointer {
			buffer.WriteString("*")
		}
		buffer.WriteString(receiver.typeName)
	}
	buffer.WriteString(") {\n")
	for _, receiver := range rendered.receivers {
		if !receiver.pointer {
			continue
		}
		buffer.WriteString("\tif ")
		buffer.WriteString(receiver.param)
		buffer.WriteString(" == nil {\n")
		buffer.WriteString("\t\tpanic(")
		buffer.WriteString(fmt.Sprintf("%q", rendered.pkg.Name+".RegisterActivities: *"+receiver.typeName+" is nil"))
		buffer.WriteString(")\n\t}\n")
	}
	for _, activity := range rendered.activities {
		buffer.WriteString("\tr.RegisterActivityWithOptions(")
		if activity.marker.ReceiverName != "" {
			buffer.WriteString(activity.receiverName)
			buffer.WriteString(".")
		}
		buffer.WriteString(activity.marker.FunctionName)
		buffer.WriteString(", ")
		buffer.WriteString(renderActivityOptions(activity))
		buffer.WriteString(")\n")
	}
	buffer.WriteString("}\n\n")
	if len(rendered.activities) == 0 {
		return
	}
	buffer.WriteString("// activityProxy is the workflow-side typed activity scheduler.\n")
	buffer.WriteString("type activityProxy struct{}\n\n")
	buffer.WriteString("// Activity is this package's generated activity proxy.\n")
	buffer.WriteString("var Activity activityProxy\n\n")
	for _, activity := range rendered.activities {
		rendered.renderActivityProxy(buffer, activity)
	}
}

func (rendered *packageRender) renderActivityProxy(buffer *bytes.Buffer, activity markerRender) {
	buffer.WriteString("// ")
	buffer.WriteString(activity.marker.ProxyName)
	buffer.WriteString(" schedules the generated activity.\n")
	buffer.WriteString("func (activityProxy) ")
	buffer.WriteString(activity.marker.ProxyName)
	buffer.WriteString("(ctx workflow.Context")
	for _, param := range activity.params {
		buffer.WriteString(", ")
		buffer.WriteString(param.name)
		buffer.WriteString(" ")
		buffer.WriteString(param.typ)
	}
	buffer.WriteString(") ")
	renderReturnType(buffer, activity)
	buffer.WriteString(" {\n")
	if activity.marker.HasOutput {
		buffer.WriteString("\tvar out ")
		buffer.WriteString(activity.outputType)
		buffer.WriteString("\n")
		buffer.WriteString("\terr := ")
		renderExecuteActivity(buffer, activity)
		buffer.WriteString(".Get(ctx, &out)\n")
		buffer.WriteString("\treturn out, err\n")
	} else {
		buffer.WriteString("\treturn ")
		renderExecuteActivity(buffer, activity)
		buffer.WriteString(".Get(ctx, nil)\n")
	}
	buffer.WriteString("}\n\n")
}

func renderExecuteActivity(buffer *bytes.Buffer, activity markerRender) {
	buffer.WriteString("workflow.ExecuteActivity(ctx, ")
	buffer.WriteString(activity.constName)
	for _, param := range activity.params {
		buffer.WriteString(", ")
		buffer.WriteString(param.name)
	}
	buffer.WriteString(")")
}

func (rendered *packageRender) renderWorkflows(buffer *bytes.Buffer) {
	buffer.WriteString("// RegisterWorkflows registers this package's generated workflows.\n")
	buffer.WriteString("func RegisterWorkflows(r ")
	if len(rendered.workflows) > 0 {
		buffer.WriteString("workflowRegistry")
	} else {
		buffer.WriteString("worker.Registry")
	}
	buffer.WriteString(") {\n")
	for _, workflow := range rendered.workflows {
		buffer.WriteString("\tr.RegisterWorkflowWithOptions(")
		buffer.WriteString(workflow.marker.FunctionName)
		buffer.WriteString(", ")
		buffer.WriteString(renderWorkflowOptions(workflow))
		buffer.WriteString(")\n")
	}
	buffer.WriteString("}\n\n")
}

func (rendered *packageRender) renderRegister(buffer *bytes.Buffer) {
	buffer.WriteString("// Register registers this package's generated activities and workflows.\n")
	buffer.WriteString("func Register(r worker.Registry")
	for _, receiver := range rendered.receivers {
		buffer.WriteString(", ")
		buffer.WriteString(receiver.param)
		buffer.WriteString(" ")
		if receiver.pointer {
			buffer.WriteString("*")
		}
		buffer.WriteString(receiver.typeName)
	}
	buffer.WriteString(") {\n")
	buffer.WriteString("\tRegisterActivities(r")
	for _, receiver := range rendered.receivers {
		buffer.WriteString(", ")
		buffer.WriteString(receiver.param)
	}
	buffer.WriteString(")\n")
	buffer.WriteString("\tRegisterWorkflows(r)\n")
	buffer.WriteString("}\n\n")
}

func (rendered *packageRender) renderClient(buffer *bytes.Buffer) {
	if len(rendered.workflows) == 0 {
		return
	}
	buffer.WriteString("// workflowStarter is a narrow seam around client.Client.ExecuteWorkflow.\n")
	buffer.WriteString("type workflowStarter interface {\n")
	buffer.WriteString("\tExecuteWorkflow(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)\n")
	buffer.WriteString("}\n\n")
	buffer.WriteString("// Client is the generated typed client surface.\n")
	buffer.WriteString("type Client struct {\n\tc workflowStarter\n}\n\n")
	buffer.WriteString("// NewClient creates the generated typed client surface.\n")
	buffer.WriteString("func NewClient(c client.Client) Client {\n\treturn Client{c: c}\n}\n\n")
	for _, workflow := range rendered.workflows {
		rendered.renderWorkflowRunHandle(buffer, workflow)
		rendered.renderWorkflowClient(buffer, workflow)
		rendered.renderWorkflowAsyncClient(buffer, workflow)
	}
}

func (rendered *packageRender) renderWorkflowRunHandle(buffer *bytes.Buffer, workflow markerRender) {
	runType := workflowRunTypeName(workflow)
	buffer.WriteString("// ")
	buffer.WriteString(runType)
	buffer.WriteString(" is the generated typed handle for a started ")
	buffer.WriteString(workflow.marker.FunctionName)
	buffer.WriteString(" workflow.\n")
	buffer.WriteString("type ")
	buffer.WriteString(runType)
	buffer.WriteString(" struct {\n\trun client.WorkflowRun\n}\n\n")
	buffer.WriteString("// GetID returns the workflow execution ID assigned by Temporal.\n")
	buffer.WriteString("func (run ")
	buffer.WriteString(runType)
	buffer.WriteString(") GetID() string {\n\treturn run.run.GetID()\n}\n\n")
	buffer.WriteString("// GetRunID returns the concrete run ID assigned by Temporal.\n")
	buffer.WriteString("func (run ")
	buffer.WriteString(runType)
	buffer.WriteString(") GetRunID() string {\n\treturn run.run.GetRunID()\n}\n\n")
	buffer.WriteString("// Get waits for the workflow to complete and returns its typed result.\n")
	buffer.WriteString("func (run ")
	buffer.WriteString(runType)
	buffer.WriteString(") Get(ctx context.Context) ")
	renderReturnType(buffer, workflow)
	buffer.WriteString(" {\n")
	if workflow.marker.HasOutput {
		buffer.WriteString("\tvar out ")
		buffer.WriteString(workflow.outputType)
		buffer.WriteString("\n")
		buffer.WriteString("\tif err := run.run.Get(ctx, &out); err != nil {\n")
		buffer.WriteString("\t\treturn ")
		buffer.WriteString(zeroValue(workflow.outputType))
		buffer.WriteString(", err\n")
		buffer.WriteString("\t}\n")
		buffer.WriteString("\treturn out, nil\n")
	} else {
		buffer.WriteString("\treturn run.run.Get(ctx, nil)\n")
	}
	buffer.WriteString("}\n\n")
}

func (rendered *packageRender) renderWorkflowClient(buffer *bytes.Buffer, workflow markerRender) {
	buffer.WriteString("// ")
	buffer.WriteString(workflow.marker.FunctionName)
	buffer.WriteString(" starts the generated workflow and awaits its result.\n")
	buffer.WriteString("func (cl Client) ")
	buffer.WriteString(workflow.marker.FunctionName)
	buffer.WriteString("(ctx context.Context, opts client.StartWorkflowOptions")
	for _, param := range workflow.params {
		buffer.WriteString(", ")
		buffer.WriteString(param.name)
		buffer.WriteString(" ")
		buffer.WriteString(param.typ)
	}
	buffer.WriteString(") ")
	renderReturnType(buffer, workflow)
	buffer.WriteString(" {\n")
	buffer.WriteString("\trun, err := cl.")
	buffer.WriteString(workflow.marker.FunctionName)
	buffer.WriteString("Async(ctx, opts")
	for _, param := range workflow.params {
		buffer.WriteString(", ")
		buffer.WriteString(param.name)
	}
	buffer.WriteString(")\n")
	buffer.WriteString("\tif err != nil {\n")
	if workflow.marker.HasOutput {
		buffer.WriteString("\t\treturn ")
		buffer.WriteString(zeroValue(workflow.outputType))
		buffer.WriteString(", err\n")
	} else {
		buffer.WriteString("\t\treturn err\n")
	}
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn run.Get(ctx)\n")
	buffer.WriteString("}\n\n")
}

func (rendered *packageRender) renderWorkflowAsyncClient(buffer *bytes.Buffer, workflow markerRender) {
	buffer.WriteString("// ")
	buffer.WriteString(workflow.marker.FunctionName)
	buffer.WriteString("Async starts the generated workflow without awaiting it.\n")
	buffer.WriteString("func (cl Client) ")
	buffer.WriteString(workflow.marker.FunctionName)
	buffer.WriteString("Async(ctx context.Context, opts client.StartWorkflowOptions")
	for _, param := range workflow.params {
		buffer.WriteString(", ")
		buffer.WriteString(param.name)
		buffer.WriteString(" ")
		buffer.WriteString(param.typ)
	}
	buffer.WriteString(") (")
	buffer.WriteString(workflowRunTypeName(workflow))
	buffer.WriteString(", error) {\n")
	buffer.WriteString("\trun, err := cl.c.ExecuteWorkflow(ctx, opts, ")
	buffer.WriteString(workflow.constName)
	for _, param := range workflow.params {
		buffer.WriteString(", ")
		buffer.WriteString(param.name)
	}
	buffer.WriteString(")\n")
	buffer.WriteString("\tif err != nil {\n")
	buffer.WriteString("\t\treturn ")
	buffer.WriteString(workflowRunTypeName(workflow))
	buffer.WriteString("{}, err\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn ")
	buffer.WriteString(workflowRunTypeName(workflow))
	buffer.WriteString("{run: run}, nil\n")
	buffer.WriteString("}\n\n")
}

func renderReturnType(buffer *bytes.Buffer, marker markerRender) {
	if marker.marker.HasOutput {
		buffer.WriteString("(")
		buffer.WriteString(marker.outputType)
		buffer.WriteString(", error)")
		return
	}
	buffer.WriteString("error")
}

func renderActivityOptions(activity markerRender) string {
	fields := []string{"Name: " + activity.constName}
	if activity.marker.Options.DisableAlreadyRegisteredCheck {
		fields = append(fields, "DisableAlreadyRegisteredCheck: true")
	}
	if activity.marker.Options.SkipInvalidStructFunctions {
		fields = append(fields, "SkipInvalidStructFunctions: true")
	}
	return "activity.RegisterOptions{" + strings.Join(fields, ", ") + "}"
}

func renderWorkflowOptions(workflow markerRender) string {
	fields := []string{"Name: " + workflow.constName}
	if workflow.marker.Options.DisableAlreadyRegisteredCheck {
		fields = append(fields, "DisableAlreadyRegisteredCheck: true")
	}
	if workflow.marker.Options.VersioningBehavior != "" {
		fields = append(fields, "VersioningBehavior: "+workflowVersioningBehavior(workflow.marker.Options.VersioningBehavior))
	}
	return "workflow.RegisterOptions{" + strings.Join(fields, ", ") + "}"
}

func workflowVersioningBehavior(value string) string {
	switch value {
	case "Pinned", "pinned", "VersioningBehaviorPinned":
		return "workflow.VersioningBehaviorPinned"
	case "AutoUpgrade", "autoUpgrade", "auto-upgrade", "VersioningBehaviorAutoUpgrade":
		return "workflow.VersioningBehaviorAutoUpgrade"
	case "Unspecified", "unspecified", "VersioningBehaviorUnspecified":
		return "workflow.VersioningBehaviorUnspecified"
	default:
		if strings.HasPrefix(value, "workflow.") {
			return value
		}
		return value
	}
}

func renderedBusinessParameters(renderer *typeRenderer, marker DiscoveredMarker) []parameterRender {
	params := marker.signature.Params()
	start := 0
	switch marker.Kind {
	case ActivityMarker:
		if params.Len() > 0 && isActivityContext(params.At(0).Type()) {
			start = 1
		}
	case WorkflowMarker:
		start = 1
	}
	var rendered []parameterRender
	for index := start; index < params.Len(); index++ {
		param := params.At(index)
		rendered = append(rendered, parameterRender{
			name: parameterName(param, index-start+1),
			typ:  renderer.render(param.Type()),
		})
	}
	return rendered
}

func parameterName(param *types.Var, fallbackIndex int) string {
	if param.Name() == "" || param.Name() == "_" {
		return fmt.Sprintf("arg%d", fallbackIndex)
	}
	return param.Name()
}

func receiverRenders(activities []markerRender) []receiverRender {
	byType := map[string]receiverRender{}
	for _, activity := range activities {
		if activity.marker.ReceiverName == "" {
			continue
		}
		signature := activity.marker.signature
		receiver := signature.Recv()
		receiverType := types.Unalias(receiver.Type())
		pointer := false
		if ptr, ok := receiverType.(*types.Pointer); ok {
			pointer = true
			receiverType = types.Unalias(ptr.Elem())
		}
		byType[activity.marker.ReceiverName] = receiverRender{
			typeName: activity.marker.ReceiverName,
			param:    receiverParamName(activity.marker.ReceiverName),
			pointer:  pointer,
		}
	}
	receivers := make([]receiverRender, 0, len(byType))
	for _, receiver := range byType {
		receivers = append(receivers, receiver)
	}
	sort.Slice(receivers, func(i int, j int) bool {
		return receivers[i].typeName < receivers[j].typeName
	})
	return receivers
}

func receiverParamName(typeName string) string {
	if typeName == "" {
		return ""
	}
	return lowerFirst(typeName)
}

func markerConstName(marker DiscoveredMarker) string {
	if marker.Kind == ActivityMarker {
		if strings.HasSuffix(marker.ProxyName, "Activity") {
			return marker.ProxyName + "Name"
		}
		return marker.ProxyName + "ActivityName"
	}
	if strings.HasSuffix(marker.FunctionName, "Workflow") {
		return marker.FunctionName + "Name"
	}
	return marker.FunctionName + "WorkflowName"
}

func workflowRunTypeName(workflow markerRender) string {
	return workflow.marker.FunctionName + "Run"
}

func hasMarkerKind(markers []DiscoveredMarker, kind MarkerKind) bool {
	for _, marker := range markers {
		if marker.Kind == kind {
			return true
		}
	}
	return false
}

func zeroValue(typeName string) string {
	if strings.HasPrefix(typeName, "*") ||
		strings.HasPrefix(typeName, "[]") ||
		strings.HasPrefix(typeName, "map[") ||
		strings.HasPrefix(typeName, "chan ") ||
		strings.HasPrefix(typeName, "func(") ||
		typeName == "interface{}" ||
		typeName == "any" {
		return "nil"
	}
	return typeName + "{}"
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}
