package toolschema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// RenderGoFile renders generated schema variables as gofmt-formatted Go code.
func RenderGoFile(packageName string, schemas map[string]json.RawMessage) ([]byte, error) {
	return RenderGeneratedGoFile(packageName, schemas, nil)
}

// RenderGeneratedGoFile renders generated schema variables and optional logical
// tool accessors as gofmt-formatted Go code.
func RenderGeneratedGoFile(
	packageName string,
	schemas map[string]json.RawMessage,
	tools []DiscoveredToolSpec,
) ([]byte, error) {
	if strings.TrimSpace(packageName) == "" {
		return nil, fmt.Errorf("output package is required")
	}
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		if strings.TrimSpace(name) == "" {
			return nil, fmt.Errorf("schema variable name is required")
		}
		names = append(names, name)
	}
	sort.Strings(names)
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by vihren-toolschema; DO NOT EDIT.\n\n")
	buffer.WriteString("package ")
	buffer.WriteString(packageName)
	buffer.WriteString("\n\n")
	writeImports(&buffer)
	if len(tools) == 0 {
		for _, name := range names {
			compact, err := compactJSON(schemas[name])
			if err != nil {
				return nil, fmt.Errorf("schema %s is invalid JSON: %w", name, err)
			}
			buffer.WriteString("var ")
			buffer.WriteString(name)
			buffer.WriteString(" = json.RawMessage(`")
			buffer.Write(compact)
			buffer.WriteString("`)\n\n")
		}
	} else {
		if err := writeToolSpecSchemaInit(&buffer, schemas, tools); err != nil {
			return nil, err
		}
	}
	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func writeImports(buffer *bytes.Buffer) {
	buffer.WriteString("import \"encoding/json\"\n\n")
}

func writeToolSpecSchemaInit(
	buffer *bytes.Buffer,
	schemas map[string]json.RawMessage,
	tools []DiscoveredToolSpec,
) error {
	buffer.WriteString("func init() {\n")
	for _, tool := range tools {
		inputSchema, err := compactNamedSchema(schemas, tool.InputSchemaVariableName)
		if err != nil {
			return err
		}
		outputSchema, err := compactNamedSchema(schemas, tool.OutputSchemaVariableName)
		if err != nil {
			return err
		}
		buffer.WriteString(tool.SpecVariableName)
		buffer.WriteString(".InputSchema = json.RawMessage(`")
		buffer.Write(inputSchema)
		buffer.WriteString("`)\n")
		buffer.WriteString(tool.SpecVariableName)
		buffer.WriteString(".OutputSchema = json.RawMessage(`")
		buffer.Write(outputSchema)
		buffer.WriteString("`)\n")
	}
	buffer.WriteString("}\n\n")
	return nil
}

func compactNamedSchema(schemas map[string]json.RawMessage, name string) ([]byte, error) {
	schema, ok := schemas[name]
	if !ok {
		return nil, fmt.Errorf("schema %s is missing", name)
	}
	compact, err := compactJSON(schema)
	if err != nil {
		return nil, fmt.Errorf("schema %s is invalid JSON: %w", name, err)
	}
	return compact, nil
}

func compactJSON(data json.RawMessage) ([]byte, error) {
	var buffer bytes.Buffer
	if err := json.Compact(&buffer, data); err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}
