// Code generated by vihren-gen. DO NOT EDIT.

package codegenhello

import (
	"context"
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

const (
	// ComposeGreetingActivityName is the derived Temporal activity type.
	ComposeGreetingActivityName = "github.com/vihren-dev/vihren/examples/codegenhello.ComposeGreeting"

	// HelloWorkflowName is the derived Temporal workflow type.
	HelloWorkflowName = "github.com/vihren-dev/vihren/examples/codegenhello.HelloWorkflow"
)

// activityRegistry is the minimal worker-side activity registration surface used by generated code.
type activityRegistry interface {
	RegisterActivityWithOptions(activityFunc any, options activity.RegisterOptions)
}

// workflowRegistry is the minimal worker-side workflow registration surface used by generated code.
type workflowRegistry interface {
	RegisterWorkflowWithOptions(workflowFunc any, options workflow.RegisterOptions)
}

// RegisterActivities registers this package's generated activities.
func RegisterActivities(r activityRegistry, greetingActivities *GreetingActivities) {
	if greetingActivities == nil {
		panic("codegenhello.RegisterActivities: *GreetingActivities is nil")
	}
	r.RegisterActivityWithOptions(greetingActivities.ComposeGreeting, activity.RegisterOptions{Name: ComposeGreetingActivityName})
}

// activityProxy is the workflow-side typed activity scheduler.
type activityProxy struct{}

// Activity is this package's generated activity proxy.
var Activity activityProxy

// ComposeGreeting schedules the generated activity.
func (activityProxy) ComposeGreeting(ctx workflow.Context, in GreetingInput) (GreetingOutput, error) {
	var out GreetingOutput
	err := workflow.ExecuteActivity(ctx, ComposeGreetingActivityName, in).Get(ctx, &out)
	return out, err
}

// RegisterWorkflows registers this package's generated workflows.
func RegisterWorkflows(r workflowRegistry) {
	r.RegisterWorkflowWithOptions(HelloWorkflow, workflow.RegisterOptions{Name: HelloWorkflowName})
}

// Register registers this package's generated activities and workflows.
func Register(r worker.Registry, greetingActivities *GreetingActivities) {
	RegisterActivities(r, greetingActivities)
	RegisterWorkflows(r)
}

// workflowStarter is a narrow seam around client.Client.ExecuteWorkflow.
type workflowStarter interface {
	ExecuteWorkflow(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)
}

// Client is the generated typed client surface.
type Client struct {
	c workflowStarter
}

// NewClient creates the generated typed client surface.
func NewClient(c client.Client) Client {
	return Client{c: c}
}

// HelloWorkflowRun is the generated typed handle for a started HelloWorkflow workflow.
type HelloWorkflowRun struct {
	run client.WorkflowRun
}

// GetID returns the workflow execution ID assigned by Temporal.
func (run HelloWorkflowRun) GetID() string {
	return run.run.GetID()
}

// GetRunID returns the concrete run ID assigned by Temporal.
func (run HelloWorkflowRun) GetRunID() string {
	return run.run.GetRunID()
}

// Get waits for the workflow to complete and returns its typed result.
func (run HelloWorkflowRun) Get(ctx context.Context) (GreetingOutput, error) {
	var out GreetingOutput
	if err := run.run.Get(ctx, &out); err != nil {
		return GreetingOutput{}, err
	}
	return out, nil
}

// HelloWorkflow starts the generated workflow and awaits its result.
func (cl Client) HelloWorkflow(ctx context.Context, opts client.StartWorkflowOptions, in GreetingInput) (GreetingOutput, error) {
	run, err := cl.HelloWorkflowAsync(ctx, opts, in)
	if err != nil {
		return GreetingOutput{}, err
	}
	return run.Get(ctx)
}

// HelloWorkflowAsync starts the generated workflow without awaiting it.
func (cl Client) HelloWorkflowAsync(ctx context.Context, opts client.StartWorkflowOptions, in GreetingInput) (HelloWorkflowRun, error) {
	run, err := cl.c.ExecuteWorkflow(ctx, opts, HelloWorkflowName, in)
	if err != nil {
		return HelloWorkflowRun{}, err
	}
	return HelloWorkflowRun{run: run}, nil
}
