// Code generated by vihren-gen. DO NOT EDIT.

package codegenhello

import (
	"context"
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

const (
	// ComposeGreetingActivityName is the derived Temporal activity type.
	ComposeGreetingActivityName = "github.com/vihren-dev/vihren/examples/codegenhello.ComposeGreeting"

	// HelloWorkflowName is the derived Temporal workflow type.
	HelloWorkflowName = "github.com/vihren-dev/vihren/examples/codegenhello.HelloWorkflow"
)

// RegisterActivities registers this package's generated activities.
func RegisterActivities(r worker.Registry, greetingActivities *GreetingActivities) {
	if greetingActivities == nil {
		panic("codegenhello.RegisterActivities: *GreetingActivities is nil")
	}
	r.RegisterActivityWithOptions(greetingActivities.ComposeGreeting, activity.RegisterOptions{Name: ComposeGreetingActivityName})
}

// activityProxy is the workflow-side typed activity scheduler.
type activityProxy struct{}

// Activity is this package's generated activity proxy.
var Activity activityProxy

// ComposeGreeting schedules the generated activity.
func (activityProxy) ComposeGreeting(ctx workflow.Context, in GreetingInput) (GreetingOutput, error) {
	var out GreetingOutput
	err := workflow.ExecuteActivity(ctx, ComposeGreetingActivityName, in).Get(ctx, &out)
	return out, err
}

// RegisterWorkflows registers this package's generated workflows.
func RegisterWorkflows(r worker.Registry) {
	r.RegisterWorkflowWithOptions(HelloWorkflow, workflow.RegisterOptions{Name: HelloWorkflowName})
}

// Register registers this package's generated activities and workflows.
func Register(r worker.Registry, greetingActivities *GreetingActivities) {
	RegisterActivities(r, greetingActivities)
	RegisterWorkflows(r)
}

// workflowStarter is a narrow seam around client.Client.ExecuteWorkflow.
type workflowStarter interface {
	ExecuteWorkflow(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)
}

// Client is the generated typed client surface.
type Client struct {
	c workflowStarter
}

// NewClient creates the generated typed client surface.
func NewClient(c client.Client) Client {
	return Client{c: c}
}

// HelloWorkflow starts the generated workflow and awaits its result.
func (cl Client) HelloWorkflow(ctx context.Context, opts client.StartWorkflowOptions, in GreetingInput) (GreetingOutput, error) {
	run, err := cl.c.ExecuteWorkflow(ctx, opts, HelloWorkflowName, in)
	if err != nil {
		return GreetingOutput{}, err
	}
	var out GreetingOutput
	if err := run.Get(ctx, &out); err != nil {
		return GreetingOutput{}, err
	}
	return out, nil
}

// HelloWorkflowAsync starts the generated workflow without awaiting it.
func (cl Client) HelloWorkflowAsync(ctx context.Context, opts client.StartWorkflowOptions, in GreetingInput) (client.WorkflowRun, error) {
	return cl.c.ExecuteWorkflow(ctx, opts, HelloWorkflowName, in)
}
