// Code generated by vihren-gen. DO NOT EDIT.

package workflowonly

import (
	"context"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

const (
	// EchoWorkflowName is the derived Temporal workflow type.
	EchoWorkflowName = "github.com/vihren-dev/vihren/internal/codegen/testdata/fixtures/workflowonly.Echo"
)

// RegisterActivities registers this package's generated activities.
func RegisterActivities(r worker.Registry) {
}

// RegisterWorkflows registers this package's generated workflows.
func RegisterWorkflows(r worker.Registry) {
	r.RegisterWorkflowWithOptions(Echo, workflow.RegisterOptions{Name: EchoWorkflowName})
}

// Register registers this package's generated activities and workflows.
func Register(r worker.Registry) {
	RegisterActivities(r)
	RegisterWorkflows(r)
}

// workflowStarter is a narrow seam around client.Client.ExecuteWorkflow.
type workflowStarter interface {
	ExecuteWorkflow(context.Context, client.StartWorkflowOptions, interface{}, ...interface{}) (client.WorkflowRun, error)
}

// Client is the generated typed client surface.
type Client struct {
	c workflowStarter
}

// NewClient creates the generated typed client surface.
func NewClient(c client.Client) Client {
	return Client{c: c}
}

// Echo starts the generated workflow and awaits its result.
func (cl Client) Echo(ctx context.Context, opts client.StartWorkflowOptions, in EchoInput) (EchoOutput, error) {
	run, err := cl.c.ExecuteWorkflow(ctx, opts, EchoWorkflowName, in)
	if err != nil {
		return EchoOutput{}, err
	}
	var out EchoOutput
	if err := run.Get(ctx, &out); err != nil {
		return EchoOutput{}, err
	}
	return out, nil
}

// EchoAsync starts the generated workflow without awaiting it.
func (cl Client) EchoAsync(ctx context.Context, opts client.StartWorkflowOptions, in EchoInput) (client.WorkflowRun, error) {
	return cl.c.ExecuteWorkflow(ctx, opts, EchoWorkflowName, in)
}
